name: IoT-Self-Healing-CI
on: [push] # Runs every time you upload code

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python and PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Compile Firmware
        run: pio run

      - name: Install Wokwi CLI
        run: curl -L https://wokwi.com/ci/install.sh | sh

      - name: Run Automated Test
        env:
          WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}
        run: python test_firmware.py